import { 
  Users, 
  Laptop, 
  Award,
  Menu,
  LogOut,
  Lock,
  BookOpen,
  GraduationCap,
  Search,
  ChevronLeft,
  ChevronRight,
  Clock,
  Twitter,
  Linkedin,
  Share,
  AlertCircle,
  AlertTriangle,
  CheckCircle,
  Key,
  ShieldCheck,
  BarChart,
  Infinity,
  Check,
  Play,
} from 'lucide-react';

export const Icons = {
  logo: ShieldCheck,
  users: Users,
  laptop: Laptop,
  certificate: Award,
  menu: Menu,
  logout: LogOut,
  security: Lock,
  education: BookOpen,
  graduation: GraduationCap,
  clock: Clock,
  search: Search,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  twitter: Twitter,
  linkedin: Linkedin,
  share: Share,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  checkCircle: CheckCircle,
  key: Key,
  shieldCheck: ShieldCheck,
  barChart: BarChart,
  graduationCap: GraduationCap,
  infinity: Infinity,
  check: Check,
  play: Play,
} as const;

export type IconKeys = keyof typeof Icons; 